create proc BringHistorico

as

select 
EMPLEADOS.ID_EMPLEADO, EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, EMPLEADOS.EMAIL, EMPLEADOS.NUMERO_TELEFONO, 
EMPLEADOS.FECHA_CONTRATO, EMPLEADOS.SALARIO,

DEPARTAMENTOS.NOMBRE_DEPARTAMENTO,

PUESTOS.TITULO_PUESTO,

HISTORICO.FECHA_INICIO, HISTORICO.FECHA_FIN

from HISTORICO

inner join EMPLEADOS on HISTORICO.ID_EMPLEADO = EMPLEADOS.ID_EMPLEADO
inner join DEPARTAMENTOS on HISTORICO.ID_DEPARTAMENTO = DEPARTAMENTOS.ID_DEPARTAMENTO
inner join PUESTOS on HISTORICO.ID_PUESTO = PUESTOS.ID_PUESTO