use SOF108
go

alter proc BringEmpleados


AS

select 

EMPLEADOS.ID_EMPLEADO, EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, EMPLEADOS.EMAIL, EMPLEADOS.NUMERO_TELEFONO, 
EMPLEADOS.FECHA_CONTRATO, EMPLEADOS.SALARIO,

DEPARTAMENTOS.NOMBRE_DEPARTAMENTO, 

PUESTOS.TITULO_PUESTO, 

LOCACIONES.DIRECCION, LOCACIONES.CIUDAD, LOCACIONES.PROVINCIA, LOCACIONES.CODIGO_POSTAL, 

PAISES.NOMBRE_PAIS,

REGIONES.NOMBRE_REGION

from EMPLEADOS 

inner join DEPARTAMENTOS on EMPLEADOS.ID_DEPARTAMENTO = DEPARTAMENTOS.ID_DEPARTAMENTO 
inner join PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO
inner join LOCACIONES on DEPARTAMENTOS.ID_LOCACION = LOCACIONES.ID_LOCACION
inner join PAISES on LOCACIONES.ID_PAIS = PAISES.ID_PAIS
inner join REGIONES on PAISES.ID_REGION = REGIONES.ID_REGION
order by EMPLEADOS.SALARIO desc