<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage/MasterPage.master" AutoEventWireup="false" CodeFile="Seccion_Electronicos.aspx.vb" Inherits="Pages_Seccion_Electronicos" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <div id="MainSectionContainer">

        <div id="ElectronicsContainer" style="float:left;">
            <div id="SectionName"><h1>PRODUCTOS ELECTRONICOS DE TODO TIPO</h1></div>

            <div id="SectionContainer">
                <div class="PresentationProducts">
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico1.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico2.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico3.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico4.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico5.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico6.png" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico7.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico8.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico9.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico10.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                </div>

                <div class="PresentationProducts">
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico11.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico12.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico13.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico14.png" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico15.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico16.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico17.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico18.png" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico19.png" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                    <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Electronics/Electronico20.png" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                </div>
            </div>
        </div>
    </div>
</asp:Content>

