<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage/MasterPage.master" AutoEventWireup="false" CodeFile="Seccion_Juegos.aspx.vb" Inherits="Pages_Seccion_Juegos" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

       <div id="MainSectionContainer">

    <div id="GamesContainer" style="float:left;">
        <div id="SectionName"><h1>LOS MEJORES VIDEO JUEGOS</h1></div>

        <div id="SectionContainer">
            <div class="PresentationProducts">
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game1.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game2.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game3.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game4.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game5.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game6.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game7.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game8.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game9.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game10.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
            </div>
            <div class="PresentationProducts">
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game11.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game12.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game13.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game14.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game15.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game16.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game17.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game18.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game19.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/VideoGames/Game20.png" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
            </div>
        </div>
    </div>

           </div>
</asp:Content>

