<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage/MasterPage.master" AutoEventWireup="false" CodeFile="Seccion_Herramientas.aspx.vb" Inherits="Pages_Seccion_Herramientas" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

      <div id="MainSectionContainer">

    <div id="ToolsContainer" style="float:left;">

        <div id="SectionName"><h1>HERRAMIENTAS NECESARIAS</h1></div>

        <div id="SectionContainer">
            <div class="PresentationProducts">
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools26.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools2.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools3.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools4.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools5.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools6.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools7.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools8.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools9.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools10.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
            </div>
            <div class="PresentationProducts">
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools11.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools12.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools13.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools14.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools15.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools16.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools17.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools18.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools19.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Tools/Tools20.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
            </div>
        </div>
    </div>

          </div>
</asp:Content>

