<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage/MasterPage.master" AutoEventWireup="false" CodeFile="Seccion_Libros.aspx.vb" Inherits="Pages_Seccion_Libros" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

       <div id="MainSectionContainer">

    <div id="BooksContainer" style="float:left;">
        <div id="SectionName"><h1>LIBROS PARA TODAS LAS NECESIDADES</h1></div>

        <div id="SectionContainer">
            <div class="PresentationProducts">
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro1.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro2.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro3.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro4.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro5.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro6.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro7.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro8.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro9.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro10.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
            </div>
            <div class="PresentationProducts">
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro11.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro12.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro13.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro14.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro15.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro16.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro17.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro18.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro19.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
                <div class="ProductDiv"><a class="ImgProduct" href="#"><img style="width: 200px; height: 175px; margin-left: 10px;" src="../IMGs/Books/Libro20.jpg" /></a><div class="Descripcion">Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto Descripcion Del Producto</div><button style="background-color:orange; margin-top: 20px; margin-right: 20px;" type="button" Class="btn btn-default">Agregar Al Carrito</button><button style="background-color:orangered; margin-top: 20px; margin-right: 20px; font-weight: bolder;" type="button" Class="btn btn-default">Comprar</button></div>
            </div>
        </div>
    </div>

           </div>
</asp:Content>

